### ISSUE TITLE
`score-compose` - example with Docker Model Runner

### ISSUE THREAD

**Issue by mathieu-benoit** [score-spec/community-provisioners#28]
It would be great to add a provisioner for `score-compose` supporting the new Docker Model Runner (this requires Docker Desktop as far as I understand):
- https://docs.docker.com/compose/how-tos/model-runner/
- https://docs.docker.com/desktop/features/model-runner/

The generated `compose.yaml` file will look like something like this:
```yaml
services:
  chat:
    image: my-chat-app
    depends_on:
      - ai-runner

  ai-runner:
    provider:
      type: model
      options:
        model: ai/smollm2
```

More examples:
- https://github.com/docker/hello-genai/tree/main
